on:
  workflow_dispatch:
  push:
    paths:
      - config/**
      - build.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-runner
      - name: Build
        run: nix -vL --show-trace build
      - uses: actions/upload-artifact@v4
        with:
          name: zmk_firmware
          path: result